const products = [
  // Men (14 items)
  // Jackets (3)
  {
    id: 1,
    type: "Jacket",
    gender: "men",
    price: 205,
    status: "In stock",
    imgUrl:
      "https://wantedshop.ru/upload/resize_cache/iblock/1a1/400_600_1/chb71ztdpmwo14nsfkiyr71jge5lrn80.jpg",
    description: "A product made of fur and genuine leather",
  },
  {
    id: 2,
    type: "Jacket",
    gender: "men",
    price: 87,
    status: "Out of stock",
    imgUrl:
      "https://wantedshop.ru/upload/resize_cache/iblock/a0b/400_600_1/ft61n4fdp5945usv33q0mwzngw19j9j8.jpg",
    description: "A product made of cotton with artificial (synthetic) fur",
  },
  {
    id: 3,
    type: "Jacket",
    gender: "men",
    price: 45,
    status: "In stock",
    imgUrl:
      "https://wantedshop.ru/upload/resize_cache/iblock/f26/350_500_1/1610mwoeulo63elzcvm3m9snksmxah41.jpg",
    description: "A product made of cotton with artificial (synthetic) fur",
  },
  // Sweaters (3)
  {
    id: 4,
    type: "Sweater",
    gender: "men",
    price: 23,
    status: "Out of stock",
    imgUrl:
      "https://wantedshop.ru/upload/resize_cache/iblock/d9b/350_500_1/4tf5d6crxtt5y7juda5ltnqlzu0wj98g.jpg",
    description: "A product made of merino wool with added polyester",
  },
  {
    id: 5,
    type: "Sweater",
    gender: "men",
    price: 99,
    status: "In stock",
    imgUrl:
      "https://wantedshop.ru/upload/iblock/18d/zow7fvfa8417xpbfnmqnu26fz1bgman8.jpg",
    description: "A sweatshirt with a loose fit",
  },
  {
    id: 6,
    type: "Sweater",
    gender: "men",
    price: 312,
    status: "In stock",
    imgUrl:
      "https://wantedshop.ru/upload/iblock/846/ezb7x6ue7ktvgm66vrrv5oflm6bvvrha.JPG",
    description: "Sweatshirt with cartoon print",
  },
  // T-shirts (4)
  {
    id: 7,
    type: "T-shirt",
    gender: "men",
    price: 33,
    status: "In stock",
    imgUrl:
      "https://wantedshop.ru/upload/resize_cache/iblock/a98/400_600_1/yq8wwmd3v6taoah6xpyuns7fsy04wf4i.jpg",
    description: "A product made of cotton",
  },
  {
    id: 8,
    type: "T-shirt",
    gender: "men",
    price: 499,
    status: "Out of stock",
    imgUrl:
      "https://wantedshop.ru/upload/resize_cache/iblock/db6/400_600_1/fe4rdjiozev4d0jb0kl021gv16igzs0l.jpg",
    description: "A product made of cotton",
  },
  {
    id: 9,
    type: "T-shirt",
    gender: "men",
    price: 5,
    status: "Out of stock",
    imgUrl:
      "https://wantedshop.ru/upload/resize_cache/iblock/3f4/350_500_1/jxor93890haxpojygglua6pqcj4ka1ch.JPG",
    description: "A product made of cotton",
  },
  {
    id: 10,
    type: "T-shirt",
    gender: "men",
    price: 90,
    status: "In stock",
    imgUrl:
      "https://wantedshop.ru/upload/resize_cache/iblock/f68/400_600_1/bayi2l1y7q4c8bmewnlzs1vdf7l68bev.JPG",
    description: "A product made of cotton",
  },
  // Jeans (4)
  {
    id: 11,
    type: "Jeans",
    gender: "men",
    price: 110,
    status: "Out of stock",
    imgUrl:
      "https://wantedshop.ru/upload/iblock/590/jkvq98aecuchfi1jqj1alc5z2bc3bg7z.jpg",
    description: "Joggers in blue",
  },
  {
    id: 12,
    type: "Jeans",
    gender: "men",
    price: 156,
    status: "In stock",
    imgUrl:
      "https://wantedshop.ru/upload/iblock/c50/octpgf93g5cvttlt2k9eci22ecklu601.JPG",
    description: "Men's jeans in black",
  },
  {
    id: 13,
    type: "Jeans",
    gender: "men",
    price: 172,
    status: "In stock",
    imgUrl:
      "https://wantedshop.ru/upload/iblock/7a9/lza87p0yp1638ugv5lvtiovg8va5lprn.JPG",
    description: "Joggers with side pockets",
  },
  {
    id: 14,
    type: "Jeans",
    gender: "men",
    price: 199,
    status: "In stock",
    imgUrl:
      "https://wantedshop.ru/upload/iblock/542/qqeoof6skwju2dzck5fbqepb7g22674x.jpg",
    description: "Buggy jeans in gray and blue",
  },

  // Women (16 items)
  // Jackets (4)
  {
    id: 15,
    type: "Jacket",
    gender: "women",
    price: 5,
    status: "Out of stock",
    imgUrl: "https://stockmann.ru/upload/product/941/5515941/5515941-01.jpg",
    description: "Insulated shortened jacket",
  },
  {
    id: 16,
    type: "Jacket",
    gender: "women",
    price: 48,
    status: "In stock",
    imgUrl: "https://stockmann.ru/upload/product/620/5489620/5489620-01.jpg",
    description: "Oversize cut insulated jacket",
  },
  {
    id: 17,
    type: "Jacket",
    gender: "women",
    price: 76,
    status: "In stock",
    imgUrl: "https://stockmann.ru/upload/product/161/5429161/5429161-01.jpg",
    description: "Leather jacket",
  },
  {
    id: 18,
    type: "Jacket",
    gender: "women",
    price: 89,
    status: "Out of stock",
    imgUrl: "https://stockmann.ru/upload/product/722/5489722/5489722-01.jpg",
    description: "Windbreaker with stand-up collar",
  },
  // Sweaters (4)
  {
    id: 19,
    type: "Sweater",
    gender: "women",
    price: 12,
    status: "In stock",
    imgUrl: "https://stockmann.ru/upload/product/869/5517869/5517869-01.jpg",
    description: "Cotton print sweatshirt",
  },
  {
    id: 20,
    type: "Sweater",
    gender: "women",
    price: 33,
    status: "Out of stock",
    imgUrl: "https://stockmann.ru/upload/product/980/5515980/5515980-01.jpg",
    description: "Cotton hoodie with print",
  },
  {
    id: 21,
    type: "Sweater",
    gender: "women",
    price: 89,
    status: "In stock",
    imgUrl: "https://stockmann.ru/upload/product/377/5489377/5489377-01.jpg",
    description: "Cotton sweatshirt with logo",
  },
  {
    id: 22,
    type: "Sweater",
    gender: "women",
    price: 99,
    status: "In stock",
    imgUrl: "https://stockmann.ru/upload/product/193/5517193/5517193-01.jpg",
    description: "Zip-up hoodie",
  },
  // T-shirts (4)
  {
    id: 23,
    type: "T-shirt",
    gender: "women",
    price: 120,
    status: "Out of stock",
    imgUrl: "https://stockmann.ru/upload/product/355/5496355/5496355-01.jpg",
    description: "Cotton striped longsleeve with logo",
  },
  {
    id: 24,
    type: "T-shirt",
    gender: "women",
    price: 155,
    status: "In stock",
    imgUrl: "https://stockmann.ru/upload/product/355/5550355/5550355-01.jpg",
    description: "Striped knit polo",
  },
  {
    id: 25,
    type: "T-shirt",
    gender: "women",
    price: 199,
    status: "In stock",
    imgUrl: "https://stockmann.ru/upload/product/174/5490174/5490174-01.jpg",
    description: "Longsleeve with stand-up collar",
  },
  {
    id: 26,
    type: "T-shirt",
    gender: "women",
    price: 130,
    status: "In stock",
    imgUrl: "https://stockmann.ru/upload/product/269/5540269/5540269-01.jpg",
    description: "Knitted polo",
  },
  // Jeans (4)
  {
    id: 27,
    type: "Jeans",
    gender: "women",
    price: 205,
    status: "In stock",
    imgUrl: "https://stockmann.ru/upload/product/599/5520599/5520599-01.jpg",
    description: "Jeans",
  },
  {
    id: 28,
    type: "Jeans",
    gender: "women",
    price: 256,
    status: "In stock",
    imgUrl: "https://stockmann.ru/upload/product/801/5586801/5586801-21.jpg",
    description: "Wide-leg jeans",
  },
  {
    id: 29,
    type: "Jeans",
    gender: "women",
    price: 389,
    status: "In stock",
    imgUrl: "https://stockmann.ru/upload/product/196/5490196/5490196-01.jpg",
    description: "Solid-colored jeans",
  },
  {
    id: 30,
    type: "Jeans",
    gender: "women",
    price: 412,
    status: "Out of stock",
    imgUrl: "https://stockmann.ru/upload/product/466/5609466/5609466-21.jpg",
    description: "Jeans",
  },
];
